#!/usr/bin/env bash
#
# Copyright 2014 (c) Kolbe Kegel
#
# Author: Kolbe Kegel <kolbe@kolbekegel.com>
#
# This file is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the
# Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

vers=(5.0 5.1 5.5 5.6 5.7)
for ver in "${vers[@]}"; do 
    echo "Checking version $ver"
    while read page; do 
        if [[ -e $page ]]; then
            : printf "%s already retrieved\n" "$page"
        else
            printf "%s needed\n" "$page"
            curl -O "http://dev.mysql.com/doc/relnotes/mysql/$ver/en/$page"
        fi
    done < <(
        curl -s "http://dev.mysql.com/doc/relnotes/mysql/$ver/en/index.html" | 
            perl -ne 'print "$1\n" if m#(news-?-?-.*?\.html)#' | 
            sort -t- -k4 -n | 
            uniq
    )
done
